production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>

development:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>

test:
  clients:
    default:
      database: bitching_test
      hosts:
        - localhost:27017
